name: MyWolf
main: de.Keyle.MyWolf.MyWolfPlugin
version: 0.5.6
author: Keyle
website: http://dev.bukkit.org/server-mods/mywolf/
softdepend: [Vault, bPermissions, PermissionsEX, WorldGuard]
commands:
  mywolf:
    description: Help for all MyWolf commands.
  wolfname:
    description: Set the name of your MyWolf
    usage: '/<command> <WolfName>'
  wolfcall:
    aliases: [wolfc, wc]
    description: Call your MyWolf.
  wolfrelease:
    description: Release your MyWolf.
    usage: '/<command> <WolfName>'
  wolfstop:
    aliases: [wolfs, ws]
    description: your MyWolf stop attacking.
  wolfpickup:
    aliases: [wolfp, wp]
    description: Toogles pickup of your MyWolf.
  wolfinventory:
    aliases: [wolfi, wi]
    description: Open the inventory of your MyWolf.
  wolfbehavior:
    aliases: [wolfb, wb]
    description: Switch the behavior mode of your MyWolf.
    usage: '/<command> [<Raid/rai/Friendly/fri/Aggressive/agg/Normal/nor>]'
  wolfinfo:
    aliases: [winfo]
    description: Shows HP and Exp of your MyWolf
    usage: '/<command> [PlayerName]'
  wolfskill:
    description: Shows the skill-levels of a online MyWolf
    usage: '/<command> <playername>'
  wolfadmin:
    aliases: [wolfa, wa]
    description: Set the Exp or Name of a MyWolf
    usage: '/<command> [PlayerName] name/exp [Value]'

permissions:
  MyWolf.*:
    description: Gives access to all Mywolf commands
    children:
      MyWolf.respawn: true
      MyWolf.use: true
      MyWolf.leash: true
      MyWolf.stop: true
      MyWolf.call: true
      MyWolf.setname: true
      MyWolf.release: true

  MyWolf.respawn:
    description: Allows MyWolf to respawn
  Mywolf.use:
    description: Allows useage of MyWolf
  MyWolf.leash:
    description: Allows useage of leash
  MyWolf.stop:
    description: Allows useage of /wolfstop
  MyWolf.call:
    description: Allows useage of /wolfcall
  MyWolf.setname:
    description: Allows useage of /wolfname
  MyWolf.release:
    description: Allows useage of /wolfrelease